### PR TITLE
338 advanced tab breaking layout

### PR DESCRIPTION
**Pull request by lschatzkin**

### CODE REVIEW

**Comment by vbrown608** [comment]
I suppose this is a slightly separate issue, but the text on the tabs looks very very tiny to me on mobile. Could we bump the size up a little bit?

**Comment by lschatzkin** [comment]
Sure thing, I got over zealous in making sure the tabs didn't wrap.

**Comment by lschatzkin** [comment]
I've consulted with Michelle and changed the styling for mobile to allow more room for the text.

**Comment by vbrown608** [comment]
Oo I like that

**Pull request merged**
