### PR TITLE
Share links

### PR DESCRIPTION
**Pull request by wioux**
Adds share links for Facebook, Twitter, and Google+ to articles, lessons, and materials. Fixes ##209.

### CODE REVIEW

**Comment by lschatzkin** [comment]
LGTM except I think these are supposed to be in the theme colors? At least that's what I see here, I don't know if there were subsequent convos #377

**Comment by wioux** [comment]
Also fixes #386. Regarding the icon theme, I'm going to ask design about it. I really like the colorful ones.

**Comment by eff-soraya** [comment]
Hey friends, just checking in on this. 
We're seeing this kind of preview in Twitter (A) which shows a generic description of the site rather than the individual page, when we'd like to see this one, emulating what eff.org previews (B).
a
b

**Comment by wioux** [comment]
@eff-soraya Sorry for the delay. I'll fix this today.

**Comment by wioux** [comment]
I switched it to use the monochrome social media icons, and fixed a merge conflict with master.

**Comment by vbrown608** [comment]
Looks good!

**Pull request merged**
